### ISSUE TITLE
Request for fine-tuned checkpoint.

### ISSUE THREAD

**Issue by jiazhen-code** [TobyYang7/Llava_Qwen2#7]
### Describe the issue

Hi there, nice Job!
Do you have any plans to release the whole fine-tuned model based on Qwen2-1.5B? It would be a valuable option for developers to conduct ablation studies, especially since the original models (7B / 13B) are significantly larger.

**Comment by TobyYang7** [comment]
https://www.modelscope.cn/models/TobyYang7/llava-qwen2-1.5b-instruct-finvis/files

**Comment by jiazhen-code** [comment]
Thank u so much! I'll close the issue.
