### ISSUE TITLE
[Question] 作者你好，能都看一下你在微调时的数据json格式

### ISSUE THREAD

**Issue by cxh2959540834** [TobyYang7/Llava_Qwen2#8]
### Question

作者你好，如题，
![image](https://github.com/user-attachments/assets/f021f7eb-abf5-4e7f-bfe7-c64fca3c25e8)
我想看一下    --data_path ./playground/llava_images/sft.json这个sft.json的大致格式，能否提供一下

**Comment by TobyYang7** [comment]
{
        "id": "mm_figureqa_sft_0",
        "image": "mm_figureqa/images/train-00002-of-00005_13939.png",
        "conversations": [
            {
                "from": "human",
                "value": "Is Orange the minimum?\nAnswer yes or no."
            }
            ]
           }

**Comment by cxh2959540834** [comment]
谢谢
